### ISSUE TITLE
words embedding normalization

### ISSUE THREAD

**Issue by adirc** [harvardnlp/sent-conv-torch#13]
I didn't see any normalization for the word vectors (maybe i missed it). should we do it for the word embedding or we should use the same vector representation as (google's) word2vec ?

**Comment by jeffreyling** [comment]
Word vector renormalization is done in trainer.lua, with the renorm function.

**Comment by adirc** [comment]
thanks but I didn't totally understand. 
should we normalize / standardize the word embeddings before the training?  what is the purpose of the renormalization ?

**Comment by jeffreyling** [comment]
Yes, we use word2vec (or randomly initialize, see convNN.lua). Renormalization is for regularizing.

**Comment by adirc** [comment]
Thanks, i got it.  another issue: 
did you try to initialize zeros vector instead of randomly representation for words which don't include in the dictionary?  why the  randomly initialize its better ?

**Comment by jeffreyling** [comment]
We haven't tried that, but you're welcome to experiment with it!
