### ISSUE TITLE
problem running with GPU

### ISSUE THREAD

**Issue by eliabruni** [harvardnlp/sent-conv-torch#16]
Hei,

First of all great job!
I am trying your code with GPU turned on but I get the error below (I tried it on different machines, and it persists), hope you can help. I found [a commit by Karpathy](https://github.com/karpathy/char-rnn/commit/0fb9a7753ec3714d89cce836f40387a05b3c21fa) which looks related, if it can help.

th main.lua -data MR.hdf5 -cudnn 1 -gpuid 1
loading data... 
data loaded!
vocab size:     18766   
vec size:       300
==> fold        1
/home/elia/torch/install/bin/luajit: invalid arguments: CudaTensor CudaTensor CudaTensor number 
expected arguments: CudaTensor | [*CudaTensor*] [*CudaLongTensor*] CudaTensor index
stack traceback:
        [C]: at 0x7f0e5efcdd30
        [C]: in function 'max'
        /home/elia/torch/install/share/lua/5.1/nn/Max.lua:30: in function 'func'
        /home/elia/torch/install/share/lua/5.1/nngraph/gmodule.lua:345: in function 'neteval'
        /home/elia/torch/install/share/lua/5.1/nngraph/gmodule.lua:380: in function 'forward'
        ./trainer.lua:61: in function 'opfunc'
        /home/elia/torch/install/share/lua/5.1/optim/adadelta.lua:31: in function 'optim_method'
        ./trainer.lua:86: in function 'train'
        main.lua:195: in function 'train_loop'
        main.lua:341: in function 'main'
        main.lua:354: in main chunk
        [C]: in function 'dofile'
        ...elia/torch/install/lib/luarocks/rocks/trepl/scm-1/bin/th:145: in main chunk
        [C]: at 0x00406670

**Comment by jeffreyling** [comment]
Try updating your versions of torch, nn, and cunn - seems like there's some version incompatibilities floating around.

**Comment by eliabruni** [comment]
Working! Thanks a lot :)

**Comment by jeffreyling** [comment]
Great! :)
