### ISSUE TITLE
 Error: "  bad argument #1 to 'squeeze'  "

### ISSUE THREAD

**Issue by harkous** [harvardnlp/sent-conv-torch#17]
Hi authors,

I'm trying to run the training with `th main.lua -data SST1.hdf5 -cudnn 0`. However, I get the error "bad argument  #*1* to 'squeeze'" with the recent version of torch (and the code). Here is the error log:

```
./trainer.lua:159: bad argument #1 to 'squeeze' (dimension out of range at ~/torch/pkg/torch/lib/TH/generic/THTensor.c:489)
stack traceback:
        [C]: in function 'squeeze'
        ./trainer.lua:159: in function 'test'
        main.lua:198: in function 'train_loop'
        main.lua:341: in function 'main'
        main.lua:354: in main chunk
```

Checking the dimension via `print(conv_layer.output:size())`, I get 
```
  50
  57
 100
[torch.LongStorage of size 3]
```

Changing the squeeze argument to 3 instead of 4 allows the training to run, but I'm not sure whether this is the intended value for different conditions.

**Comment by jeffreyling** [comment]
Seems like an issue with non-cudnn, I pushed a change that should fix it.

**Comment by harkous** [comment]
Yes, that fixes it too. Thanks!
