### ISSUE TITLE
Memory error on GPU during testing

### ISSUE THREAD

**Issue by shashankg7** [harvardnlp/sent-conv-torch#18]
Hi,

When I run this code on GPU, it's running fine for training, but while testing it gives memory error. 
Can you think of any reason for it?

out of memory at /home/shashank/torch/extra/cutorch/lib/THC/generic/THCStorage.cu:41
stack traceback:
	[C]: at 0x7f3894b51280
	[C]: in function 'cat'
	./trainer.lua:167: in function 'test'
	main1.lua:198: in function 'train_loop'
	main1.lua:340: in function 'main'
	main1.lua:353: in main chunk
	[C]: in function 'dofile'
	...hank/torch/install/lib/luarocks/rocks/trepl/scm-1/bin/th:145: in main chunk
	[C]: at 0x00406670

**Comment by jeffreyling** [comment]
What command did you run it on? Did you use the sample data or your own?

**Comment by shashankg7** [comment]
Hi, 

Thanks for replying back. I ran 

th main.lua -data custom.hdf5 -cudnn 1

I am running it on a custom dataset with around 62K training samples and around 16K testing samples (no dev set). 

Vocab size identified by the code is: 106203.

**Comment by shashankg7** [comment]
I resolved this issue. My sentences length (max) was too long for GPU to handle, I trimmed it and it is working fine now. Thanks !!
