### ISSUE TITLE
Bug in Custom Dataset name

### ISSUE THREAD

**Issue by harkous** [harvardnlp/sent-conv-torch#20]
Hello,

In the current version, the 'custom_name' argument does not work for the file `preprocess.py`. 
To resolve it, you can move the following lines 174 and 175 to line 184.
```
 if dataset == 'custom':
    dataset = args.custom_name
```

Currently, `dataset` is changed from `custom` to a new name, and then you check again for `dataset=='custom'` on line 179.

**Comment by jeffreyling** [comment]
Thanks for the catch, I've corrected it!
