### ISSUE TITLE
Bug with more than 10 classes

### ISSUE THREAD

**Issue by harkous** [harvardnlp/sent-conv-torch#21]
Hello!

The preprocessing code assumes that the class label is of one character. This fails (without notice) with more than 10 classes. It only takes the first character of the class.

The bug is on this [line](https://github.com/harvardnlp/sent-conv-torch/blob/master/preprocess.py#L101):
` y = int(line[0]) + 1`

I was able to fix by changing the function `line_to_words` to:
```
def line_to_words(line, dataset):
  if dataset == 'SST1' or dataset == 'SST2':
    clean_line = clean_str_sst(line.strip())
  else:
    clean_line = clean_str(line.strip())
  words = clean_line.split(' ')
  label= words[0]
  words = words[1:]

  return words,label
```

Then I changed [line 51](https://github.com/harvardnlp/sent-conv-torch/blob/master/preprocess.py#L51) to:
`words,_ = line_to_words(line, dataset)`

and then changed lines 100,101 to:
```
words,y = line_to_words(line, dataset)
y=int(y)+1
```

**Comment by jeffreyling** [comment]
Pushed a change to fix it!
