### ISSUE TITLE
invalid device ordinal at /tmp/luarocks_cutorch-scm-1-6130/cutorch/init.c:719

### ISSUE THREAD

**Issue by loveJasmine** [harvardnlp/sent-conv-torch#23]
rzai@rzai00:~/prj/sent-conv-torch$ th main.lua -data MR.hdf5 -cudnn 1
THCudaCheck FAIL file=/tmp/luarocks_cutorch-scm-1-6130/cutorch/init.c line=719 error=10 : invalid device ordinal
/home/rzai/torch/install/bin/luajit: main.lua:282: cuda runtime error (10) : invalid device ordinal at /tmp/luarocks_cutorch-scm-1-6130/cutorch/init.c:719
stack traceback:
	[C]: in function 'setDevice'
	main.lua:282: in function 'main'
	main.lua:354: in main chunk
	[C]: in function 'dofile'
	...rzai/torch/install/lib/luarocks/rocks/trepl/scm-1/bin/th:145: in main chunk
	[C]: at 0x00406670
rzai@rzai00:~/prj/sent-conv-torch$

I got two gtx1080

**Comment by jeffreyling** [comment]
You will need to set -gpuid 1 or 2, I'll update the documentation to specify that.
