### ISSUE TITLE
module 'model/convNN.lua' not found:No LuaRocks module found for model/convNN.lua

### ISSUE THREAD

**Issue by loveJasmine** [harvardnlp/sent-conv-torch#24]
rzai@rzai00:~/prj/sent-conv-torch$ CUDA_VISIBLE_DEVICES=1 th main.lua -data MR.hdf5 -cudnn 0
loading data...	
data loaded!	
vocab size: 	18766	
vec size: 	300	
==> fold 	1	
epoch:	1	train perf:	70.476744186047	%, val perf 	81.062124248497	%	
epoch:	2	train perf:	81.337209302326	%, val perf 	82.765531062124	%	
epoch:	3	train perf:	87.093023255814	%, val perf 	81.763527054108	%	
epoch:	4	train perf:	91.337209302326	%, val perf 	82.765531062124	%	
epoch:	5	train perf:	94.709302325581	%, val perf 	82.364729458918	%	
epoch:	6	train perf:	96.546511627907	%, val perf 	82.865731462926	%	
epoch:	7	train perf:	98.186046511628	%, val perf 	82.865731462926	%	
epoch:	8	train perf:	98.872093023256	%, val perf 	82.965931863727	%	
epoch:	9	train perf:	99.267441860465	%, val perf 	83.567134268537	%	
epoch:	10	train perf:	99.558139534884	%, val perf 	83.867735470942	%	
epoch:	11	train perf:	99.779069767442	%, val perf 	84.168336673347	%	
epoch:	12	train perf:	99.755813953488	%, val perf 	84.268537074148	%	
epoch:	13	train perf:	99.779069767442	%, val perf 	84.168336673347	%	
epoch:	14	train perf:	99.872093023256	%, val perf 	84.068136272545	%	
epoch:	15	train perf:	99.883720930233	%, val perf 	84.068136272545	%	
epoch:	16	train perf:	99.883720930233	%, val perf 	83.967935871743	%	
epoch:	17	train perf:	99.953488372093	%, val perf 	84.268537074148	%	
epoch:	18	train perf:	99.953488372093	%, val perf 	84.268537074148	%	
epoch:	19	train perf:	99.93023255814	%, val perf 	84.468937875752	%	
epoch:	20	train perf:	99.96511627907	%, val perf 	83.967935871743	%	
epoch:	21	train perf:	99.941860465116	%, val perf 	84.168336673347	%	
epoch:	22	train perf:	99.96511627907	%, val perf 	84.36873747495	%	
epoch:	23	train perf:	99.96511627907	%, val perf 	84.468937875752	%	
epoch:	24	train perf:	99.96511627907	%, val perf 	84.068136272545	%	
epoch:	25	train perf:	99.976744186047	%, val perf 	84.468937875752	%	
best dev err:	84.468937875752	%, epoch 	19	
test perf 	81.707317073171	%	
saving checkpoint to 	results/20161106_2343_model_1.t7	
==> fold 	2	
/home/rzai/torch/install/bin/luajit: /home/rzai/torch/install/share/lua/5.1/trepl/init.lua:384: module 'model/convNN.lua' not found:No LuaRocks module found for model/convNN.lua
	no field package.preload['model/convNN.lua']
	no file '/home/rzai/.luarocks/share/lua/5.1/model/convNN/lua.lua'
	no file '/home/rzai/.luarocks/share/lua/5.1/model/convNN/lua/init.lua'
	no file '/home/rzai/torch/install/share/lua/5.1/model/convNN/lua.lua'
	no file '/home/rzai/torch/install/share/lua/5.1/model/convNN/lua/init.lua'
	no file './model/convNN/lua.lua'
	no file '/home/rzai/torch/install/share/luajit-2.1.0-beta1/model/convNN/lua.lua'
	no file '/usr/local/share/lua/5.1/model/convNN/lua.lua'
	no file '/usr/local/share/lua/5.1/model/convNN/lua/init.lua'
	no file '/home/rzai/.luarocks/lib/lua/5.1/model/convNN/lua.so'
	no file '/home/rzai/torch/install/lib/lua/5.1/model/convNN/lua.so'
	no file '/home/rzai/torch/install/lib/model/convNN/lua.so'
	no file './model/convNN/lua.so'
	no file '/usr/local/lib/lua/5.1/model/convNN/lua.so'
	no file '/usr/local/lib/lua/5.1/loadall.so'
	no file '/home/rzai/.luarocks/lib/lua/5.1/model/convNN.so'
	no file '/home/rzai/torch/install/lib/lua/5.1/model/convNN.so'
	no file '/home/rzai/torch/install/lib/model/convNN.so'
	no file './model/convNN.so'
	no file '/usr/local/lib/lua/5.1/model/convNN.so'
	no file '/usr/local/lib/lua/5.1/loadall.so'
stack traceback:
	[C]: in function 'error'
	/home/rzai/torch/install/share/lua/5.1/trepl/init.lua:384: in function 'require'
	main.lua:80: in function 'build_model'
	main.lua:178: in function 'train_loop'
	main.lua:341: in function 'main'
	main.lua:354: in main chunk
	[C]: in function 'dofile'
	...rzai/torch/install/lib/luarocks/rocks/trepl/scm-1/bin/th:145: in main chunk
	[C]: at 0x00406670
rzai@rzai00:~/prj/sent-conv-torch$ 
rzai@rzai00:~/prj/sent-conv-torch$ ll model/
total 24
drwxrwxr-x 2 rzai rzai 4096 10月 25 20:36 ./
drwxrwxr-x 6 rzai rzai 4096 11月  6 18:43 ../
-rw-rw-r-- 1 rzai rzai 4345 10月 25 20:36 convNN.lua
-rw-rw-r-- 1 rzai rzai 1392 10月 25 20:36 highway_conv.lua
-rw-rw-r-- 1 rzai rzai  957 10月 25 20:36 highway_mlp.lua
rzai@rzai00:~/prj/sent-conv-torch$

**Comment by jeffreyling** [comment]
Thanks, I have fixed the bug.
