### ISSUE TITLE
Doesn't classify on 10+ classes

### ISSUE THREAD

**Issue by damnupucci** [harvardnlp/sent-conv-torch#27]
When training on 10+, network seems to reduce number of classes to 10. 

I found it by printing out target[i] on line 175 in trainer.lua - it shows that classes always numbered from 1 to 10:
`    for i = 1, batch_size do`
`     confusion:add(outputs[i], targets[i])`
`    print('target '..targets[i])`
`    end`

Also you can see it in debug mode: confusion matrix is always 10x10 sized.

Haven't locate where exactly the issue is yet.

**Comment by jeffreyling** [comment]
The bug was in the preprocessing step - I've fixed it so it should no longer be an issue.

**Comment by damnupucci** [comment]
Indeed! Sorry.
