### ISSUE TITLE
When I train on custom data set that vocab size is 158690 ,it also runs error of out of momery.

### ISSUE THREAD

**Issue by milk120706** [harvardnlp/sent-conv-torch#28]
Hi ,I trained on a custom data set that vocab size is 158690 ,it also runs error as the figure shows.so ,the system only can train on the small date set? Can you tell me what the problem is.Thank you very much.
![error](https://cloud.githubusercontent.com/assets/23397247/21709146/0fafec84-d422-11e6-9f40-c500059b2060.png)

**Comment by jeffreyling** [comment]
You might be working with an old version of code, try pulling and running again.

**Comment by milk120706** [comment]
I downloaded the new code,it runs well.Thank you very much.
