### ISSUE TITLE
nn.Linear(input, output) should be nn.Linear(input, output, false)?

### ISSUE THREAD

**Issue by tastyminerals** [harvardnlp/sent-conv-torch#31]
Short question. In `highway_mlp.lua` line 18:
```
transform_gate = nn.Sigmoid()(nn.AddConstant(bias)(nn.Linear(size, size)(inputs[i])))
```
Shouldn't you have defined linear as `nn.Linear(size, size, false)`?
Because if not given, `nn.Linear` will add its internal bias by default.

**Comment by jeffreyling** [comment]
You're misinterpreting what the bias does here - please read the Srivastava paper on highway networks for more information: https://arxiv.org/pdf/1505.00387.pdf
